### ISSUE TITLE
0.5.0 (release in Cocoapods) won't compile in Swift 5.1

### ISSUE THREAD

**Issue by ggruen** [snipsco/Postal#90]
Hi - 

When installing via Cocoapods, the install succeeds, but when I run a build, I get a bunch of compilation errors. Looks like Cocoapods has version 0.5.0, which appears to be a couple years old, and there are 22 commits to master since that release in GitHub.

When I install using the "manual" method, everything compiles smoothly and I can fetch my inbox using the sample code as expected.

Maybe it's time for a release? :)

**Comment by AaronDDM** [comment]
You can still use Cocoapods to pull from the master branch - but yes, a release is probably better!
`pod 'Postal', :git => "https://github.com/snipsco/Postal.git", :branch => 'master'`

**Comment by lionserdar** [comment]
any update on a new release?
